### ISSUE TITLE
Stokehook seems to be offline for my application

### ISSUE THREAD

**Issue by beelauuu** [jpoehnelt/stokehook#26]
My pretty basic code which relies on Stokehook seems to be okay but it suddenly stopped working a couple days ago, and whenever you try to authorize Stokehook with your Strava it throws this error:

TypeError: server.init is not a function
    at init (file:///var/task/.netlify/serverless.js:268:28)
    at file:///var/task/.netlify/functions-internal/render.mjs:3:24
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async _tryAwaitImport (file:///var/runtime/index.mjs:875:16)
    at async _tryRequire (file:///var/runtime/index.mjs:924:86)
    at async _loadUserApp (file:///var/runtime/index.mjs:945:16)
    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)
    at async start (file:///var/runtime/index.mjs:1137:23)

**Comment by jpoehnelt** [comment]
I think reverting the netlify adapter for sveltekit fixed the problem.
